services:
  migrations:
    build: backend/internal/db
    profiles:
      - dev
    env_file: .env
    networks:
      - network
    depends_on:
      - db
    command: sleep infinity

  api:
    build: backend
    entrypoint: /app/path_api
    networks:
      - path_network
    environment:
      GOOSE_DRIVER: "postgres"
      GOOSE_MIGRATION_DIR: "./internal/db/migrations"
      GOOSE_DBSTRING: "postgresql://wave:123123@path-db-1:5432/path?sslmode=disable"
      SECRET: "mypath"
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:18-alpine
    env_file: .env
    networks:
      - network
    ports:
      - 5433:5432
    restart: unless-stopped
  frontend:
    entrypoint: node /app/build/index.js
    build: frontend
    networks:
      - network
    ports:
      - 3001:3000

networks:
  network:
    driver: bridge

volumes:
  pg_data:
