// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mapel struct {
	ID   int32
	Name pgtype.Text
}

type User struct {
	UserID   int32
	Name     pgtype.Text
	Email    pgtype.Text
	Phone    pgtype.Text
	Password pgtype.Text
}
