// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TipeKelamin string

const (
	TipeKelaminL TipeKelamin = "l"
	TipeKelaminP TipeKelamin = "p"
)

func (e *TipeKelamin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipeKelamin(s)
	case string:
		*e = TipeKelamin(s)
	default:
		return fmt.Errorf("unsupported scan type for TipeKelamin: %T", src)
	}
	return nil
}

type NullTipeKelamin struct {
	TipeKelamin TipeKelamin
	Valid       bool // Valid is true if TipeKelamin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipeKelamin) Scan(value interface{}) error {
	if value == nil {
		ns.TipeKelamin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipeKelamin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipeKelamin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipeKelamin), nil
}

type TipeMateri string

const (
	TipeMateriKuis   TipeMateri = "kuis"
	TipeMateriMateri TipeMateri = "materi"
	TipeMateriTugas  TipeMateri = "tugas"
)

func (e *TipeMateri) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipeMateri(s)
	case string:
		*e = TipeMateri(s)
	default:
		return fmt.Errorf("unsupported scan type for TipeMateri: %T", src)
	}
	return nil
}

type NullTipeMateri struct {
	TipeMateri TipeMateri
	Valid      bool // Valid is true if TipeMateri is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipeMateri) Scan(value interface{}) error {
	if value == nil {
		ns.TipeMateri, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipeMateri.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipeMateri) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipeMateri), nil
}

type Kela struct {
	ID       int32
	Nama     string
	Bagian   pgtype.Text
	Pengajar int32
	Kode     string
	Dibuat   pgtype.Timestamp
}

type Murid struct {
	ID         int32
	IDPengguna int32
	KodeKelas  string
	Bergabung  pgtype.Timestamp
}

type Pengguna struct {
	ID           int32
	Nama         string
	Email        string
	JenisKelamin TipeKelamin
	Telepon      string
	Password     string
	Dibuat       pgtype.Timestamp
}

type Post struct {
	ID        int32
	Nama      string
	Deskripsi string
	KodeKelas string
	Tipe      TipeMateri
	Tenggat   pgtype.Timestamp
	Dibuat    pgtype.Timestamp
}
