// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const checkPengguna = `-- name: CheckPengguna :one
select id, password from pengguna where email = $1
`

type CheckPenggunaRow struct {
	ID       int32
	Password string
}

func (q *Queries) CheckPengguna(ctx context.Context, email string) (CheckPenggunaRow, error) {
	row := q.db.QueryRow(ctx, checkPengguna, email)
	var i CheckPenggunaRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const createKelas = `-- name: CreateKelas :exec
insert into kelas (nama, subjek, pengajar, kode) values ($1, $2, $3, $4)
`

type CreateKelasParams struct {
	Nama     string
	Subjek   string
	Pengajar int32
	Kode     string
}

func (q *Queries) CreateKelas(ctx context.Context, arg CreateKelasParams) error {
	_, err := q.db.Exec(ctx, createKelas,
		arg.Nama,
		arg.Subjek,
		arg.Pengajar,
		arg.Kode,
	)
	return err
}

const createPengguna = `-- name: CreatePengguna :one
insert into pengguna(nama, email, telepon, password) values ($1, $2, $3, $4) returning id
`

type CreatePenggunaParams struct {
	Nama     string
	Email    string
	Telepon  string
	Password string
}

func (q *Queries) CreatePengguna(ctx context.Context, arg CreatePenggunaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPengguna,
		arg.Nama,
		arg.Email,
		arg.Telepon,
		arg.Password,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getKelas = `-- name: GetKelas :one
select id, nama, subjek, pengajar, kode, dibuat from kelas where kode = $1
`

func (q *Queries) GetKelas(ctx context.Context, kode string) (Kela, error) {
	row := q.db.QueryRow(ctx, getKelas, kode)
	var i Kela
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Subjek,
		&i.Pengajar,
		&i.Kode,
		&i.Dibuat,
	)
	return i, err
}

const getPengguna = `-- name: GetPengguna :one
select id, nama, email, telepon, password, dibuat from pengguna where id = $1
`

func (q *Queries) GetPengguna(ctx context.Context, id int32) (Pengguna, error) {
	row := q.db.QueryRow(ctx, getPengguna, id)
	var i Pengguna
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Email,
		&i.Telepon,
		&i.Password,
		&i.Dibuat,
	)
	return i, err
}

const listKelas = `-- name: ListKelas :many
SELECT id, nama, subjek, pengajar, kode, dibuat FROM kelas WHERE kelas.pengajar = $1
UNION
SELECT kelas.id, nama, subjek, pengajar, kode, dibuat, murid.id, id_pengguna, id_kelas, bergabung FROM kelas JOIN murid ON murid.id_kelas = kelas.id
WHERE murid.id_pengguna = $1
`

func (q *Queries) ListKelas(ctx context.Context, pengajar int32) ([]Kela, error) {
	rows, err := q.db.Query(ctx, listKelas, pengajar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kela
	for rows.Next() {
		var i Kela
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Subjek,
			&i.Pengajar,
			&i.Kode,
			&i.Dibuat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMurid = `-- name: ListMurid :many
select id, id_pengguna, id_kelas, bergabung from murid where id_kelas = $1
`

func (q *Queries) ListMurid(ctx context.Context, idKelas int32) ([]Murid, error) {
	rows, err := q.db.Query(ctx, listMurid, idKelas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Murid
	for rows.Next() {
		var i Murid
		if err := rows.Scan(
			&i.ID,
			&i.IDPengguna,
			&i.IDKelas,
			&i.Bergabung,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPengguna = `-- name: ListPengguna :many
select id, nama, email, telepon, password, dibuat from pengguna
`

func (q *Queries) ListPengguna(ctx context.Context) ([]Pengguna, error) {
	rows, err := q.db.Query(ctx, listPengguna)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pengguna
	for rows.Next() {
		var i Pengguna
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Email,
			&i.Telepon,
			&i.Password,
			&i.Dibuat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPost = `-- name: ListPost :many
select id, nama, deskripsi, id_kelas, tipe from post where id_kelas = $1
`

func (q *Queries) ListPost(ctx context.Context, idKelas int32) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPost, idKelas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Deskripsi,
			&i.IDKelas,
			&i.Tipe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
