// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPengguna = `-- name: CheckPengguna :one
select id, password from pengguna where email = $1
`

type CheckPenggunaRow struct {
	ID       int32
	Password string
}

func (q *Queries) CheckPengguna(ctx context.Context, email string) (CheckPenggunaRow, error) {
	row := q.db.QueryRow(ctx, checkPengguna, email)
	var i CheckPenggunaRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const createKelas = `-- name: CreateKelas :exec
insert into kelas (nama, bagian, pengajar, kode) values ($1, $2, $3, $4)
`

type CreateKelasParams struct {
	Nama     string
	Bagian   pgtype.Text
	Pengajar int32
	Kode     string
}

func (q *Queries) CreateKelas(ctx context.Context, arg CreateKelasParams) error {
	_, err := q.db.Exec(ctx, createKelas,
		arg.Nama,
		arg.Bagian,
		arg.Pengajar,
		arg.Kode,
	)
	return err
}

const createPengguna = `-- name: CreatePengguna :one
insert into pengguna(nama, email, telepon, password, jenis_kelamin) values ($1, $2, $3, $4, $5) returning id
`

type CreatePenggunaParams struct {
	Nama         string
	Email        string
	Telepon      string
	Password     string
	JenisKelamin TipeKelamin
}

func (q *Queries) CreatePengguna(ctx context.Context, arg CreatePenggunaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPengguna,
		arg.Nama,
		arg.Email,
		arg.Telepon,
		arg.Password,
		arg.JenisKelamin,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createPost = `-- name: CreatePost :exec
insert into post (nama, deskripsi, kode_kelas, tipe) values ($1, $2, $3, $4)
`

type CreatePostParams struct {
	Nama      string
	Deskripsi string
	KodeKelas string
	Tipe      TipeMateri
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.Nama,
		arg.Deskripsi,
		arg.KodeKelas,
		arg.Tipe,
	)
	return err
}

const getKelas = `-- name: GetKelas :one
select k.nama as nama_kelas, bagian, p.nama as nama_pengajar from kelas k
join pengguna p on p.id = k.pengajar where kode = $1
`

type GetKelasRow struct {
	NamaKelas    string
	Bagian       pgtype.Text
	NamaPengajar string
}

func (q *Queries) GetKelas(ctx context.Context, kode string) (GetKelasRow, error) {
	row := q.db.QueryRow(ctx, getKelas, kode)
	var i GetKelasRow
	err := row.Scan(&i.NamaKelas, &i.Bagian, &i.NamaPengajar)
	return i, err
}

const getKelasCode = `-- name: GetKelasCode :many
select id, nama, bagian, pengajar, kode, dibuat from kelas where kode = $1
`

func (q *Queries) GetKelasCode(ctx context.Context, kode string) ([]Kela, error) {
	rows, err := q.db.Query(ctx, getKelasCode, kode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kela
	for rows.Next() {
		var i Kela
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Bagian,
			&i.Pengajar,
			&i.Kode,
			&i.Dibuat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPengguna = `-- name: GetPengguna :one
select id, nama, email, jenis_kelamin, telepon from pengguna where id = $1
`

type GetPenggunaRow struct {
	ID           int32
	Nama         string
	Email        string
	JenisKelamin TipeKelamin
	Telepon      string
}

func (q *Queries) GetPengguna(ctx context.Context, id int32) (GetPenggunaRow, error) {
	row := q.db.QueryRow(ctx, getPengguna, id)
	var i GetPenggunaRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Email,
		&i.JenisKelamin,
		&i.Telepon,
	)
	return i, err
}

const listKelas = `-- name: ListKelas :many
SELECT kelas.id, kelas.nama as nama_kelas, bagian, pengguna.nama as nama_pengguna, kode, kelas.dibuat FROM kelas join pengguna on kelas.pengajar = pengguna.id WHERE kelas.pengajar = $1
UNION
SELECT kelas.id, kelas.nama as nama_kelas, bagian, pengguna.nama as nama_pengguna, kode, kelas.dibuat FROM kelas JOIN murid ON murid.kode_kelas = kelas.kode join pengguna on kelas.pengajar = pengguna.id
WHERE murid.id_pengguna = $1
`

type ListKelasRow struct {
	ID           int32
	NamaKelas    string
	Bagian       pgtype.Text
	NamaPengguna string
	Kode         string
	Dibuat       pgtype.Timestamp
}

func (q *Queries) ListKelas(ctx context.Context, pengajar int32) ([]ListKelasRow, error) {
	rows, err := q.db.Query(ctx, listKelas, pengajar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKelasRow
	for rows.Next() {
		var i ListKelasRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaKelas,
			&i.Bagian,
			&i.NamaPengguna,
			&i.Kode,
			&i.Dibuat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMurid = `-- name: ListMurid :many
select id, id_pengguna, kode_kelas, bergabung from murid where kode_kelas = $1
`

func (q *Queries) ListMurid(ctx context.Context, kodeKelas string) ([]Murid, error) {
	rows, err := q.db.Query(ctx, listMurid, kodeKelas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Murid
	for rows.Next() {
		var i Murid
		if err := rows.Scan(
			&i.ID,
			&i.IDPengguna,
			&i.KodeKelas,
			&i.Bergabung,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPengguna = `-- name: ListPengguna :many
select id, nama, email, jenis_kelamin, telepon, password, dibuat from pengguna
`

func (q *Queries) ListPengguna(ctx context.Context) ([]Pengguna, error) {
	rows, err := q.db.Query(ctx, listPengguna)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pengguna
	for rows.Next() {
		var i Pengguna
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Email,
			&i.JenisKelamin,
			&i.Telepon,
			&i.Password,
			&i.Dibuat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPost = `-- name: ListPost :many
select id, nama, deskripsi, kode_kelas, tipe from post where kode_kelas = $1
`

func (q *Queries) ListPost(ctx context.Context, kodeKelas string) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPost, kodeKelas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Deskripsi,
			&i.KodeKelas,
			&i.Tipe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validatePenggunaID = `-- name: ValidatePenggunaID :one
select id from pengguna where id = $1
`

func (q *Queries) ValidatePenggunaID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, validatePenggunaID, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}
